<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE PCFCommands [
	<!ELEMENT PCFCommands (Command+)>
	<!ELEMENT Command (RequestParameters?, ResponseParameters?)>
	<!ATTLIST Command name CDATA #REQUIRED
					  integerCode CDATA #REQUIRED
					  identifier CDATA #IMPLIED
	>
	<!ELEMENT RequestParameters (Parameter+)>
	<!ELEMENT ResponseParameters (Parameter+)>
	
	<!ELEMENT Parameter EMPTY>
	<!ATTLIST Parameter name CDATA #REQUIRED
						type CDATA #REQUIRED
						integerCode CDATA #REQUIRED
						identifier CDATA #IMPLIED
						required CDATA #IMPLIED
	>					
]>
<PCFCommands>
	<!-- Backup CF Structure  -->
	<Command name="BACKUP_CF_STRUC" integerCode="105" identifier="MQCMD_BACKUP_CF_STRUC">
		<RequestParameters>
			<Parameter name="CFStrucName" integerCode="2039" identifier="MQCA_CF_STRUC_NAME" type="string" required="true"/>

			<Parameter name="CommandScope" type="string" integerCode="3080" identifier="MQCACF_COMMAND_SCOPE"/>
			<Parameter name="ExcludeInterval" type="int" integerCode="1134" identifier="MQIACF_EXCLUDE_INTERVAL"/>
		</RequestParameters>
	</Command>

	<!-- Change, Copy, and Create Authentication Information Object -->
	<Command name="CHANGE_AUTH_INFO" integerCode="79" identifier="MQCMD_CHANGE_AUTH_INFO">
		<RequestParameters>
			<Parameter name="AuthInfoName" integerCode="2045" identifier="MQCA_AUTH_INFO_NAME" type="string" required="true"/>

			<Parameter name="AuthInfoConnName" type="string" integerCode="2053" identifier="MQCA_AUTH_INFO_CONN_NAME"/>
			<Parameter name="AuthInfoDesc" type="string" integerCode="2046" identifier="MQCA_AUTH_INFO_DESC"/>
			<Parameter name="CommandScope" type="string" integerCode="3080" identifier="MQCACF_COMMAND_SCOPE"/>
			<Parameter name="LDAPPassword" type="string" integerCode="2048" identifier="MQCA_LDAP_PASSWORD"/>
			<Parameter name="LDAPUserName" type="string" integerCode="2047" identifier="MQCA_LDAP_USER_NAME"/>
			<Parameter name="QSGDisposition" type="int" integerCode="63" identifier="MQIA_QSG_DISP"/>
		</RequestParameters>
	</Command>

	<Command name="COPY_AUTH_INFO" integerCode="80" identifier="MQCMD_COPY_AUTH_INFO">
		<RequestParameters>
			<Parameter name="FromAuthInfoName" type="string" integerCode="3009" identifier="MQCACF_FROM_AUTH_INFO_NAME" required="true"/>
			<Parameter name="ToAuthInfoName" type="string" integerCode="3010" identifier="MQCACF_TO_AUTH_INFO_NAME" required="true"/>
			<Parameter name="AuthInfoType" integerCode="66" identifier="MQIA_AUTH_INFO_TYPE" type="int" required="true"/>

			<Parameter name="AuthInfoConnName" type="string" integerCode="2053" identifier="MQCA_AUTH_INFO_CONN_NAME"/>
			<Parameter name="AuthInfoDesc" type="string" integerCode="2046" identifier="MQCA_AUTH_INFO_DESC"/>
			<Parameter name="CommandScope" type="string" integerCode="3080" identifier="MQCACF_COMMAND_SCOPE"/>
			<Parameter name="LDAPPassword" type="string" integerCode="2048" identifier="MQCA_LDAP_PASSWORD"/>
			<Parameter name="LDAPUserName" type="string" integerCode="2047" identifier="MQCA_LDAP_USER_NAME"/>
			<Parameter name="QSGDisposition" type="int" integerCode="63" identifier="MQIA_QSG_DISP"/>
		</RequestParameters>
	</Command>


	<Command name="CREATE_AUTH_INFO" integerCode="81" identifier="MQCMD_CREATE_AUTH_INFO">
		<RequestParameters>
			<Parameter name="AuthInfoName" integerCode="2045" identifier="MQCA_AUTH_INFO_NAME" type="string" required="true"/>
			<Parameter name="AuthInfoType" integerCode="66" identifier="MQIA_AUTH_INFO_TYPE" type="int" required="true"/>
			<Parameter name="AuthInfoConnName" integerCode="2053" identifier="MQCA_AUTH_INFO_CONN_NAME" type="string" required="true"/>

			<Parameter name="AuthInfoDesc" type="string" integerCode="2046" identifier="MQCA_AUTH_INFO_DESC"/>
			<Parameter name="CommandScope" type="string" integerCode="3080" identifier="MQCACF_COMMAND_SCOPE"/>
			<Parameter name="LDAPPassword" type="string" integerCode="2048" identifier="MQCA_LDAP_PASSWORD"/>
			<Parameter name="LDAPUserName" type="string" integerCode="2047" identifier="MQCA_LDAP_USER_NAME"/>
			<Parameter name="QSGDisposition" type="int" integerCode="63" identifier="MQIA_QSG_DISP"/>
		</RequestParameters>
	</Command>


	<!-- Change, Copy, and Create CF Structure -->
	<Command name="CHANGE_CF_STRUC" integerCode="101" identifier="MQCMD_CHANGE_CF_STRUC">
		<RequestParameters>
			<Parameter name="CFStrucName" integerCode="2039" identifier="MQCA_CF_STRUC_NAME" type="string" required="true"/>

			<Parameter name="CFLevel" type="int" integerCode="70" identifier="MQIA_CF_LEVEL"/>
			<Parameter name="CFStrucDesc" type="string" integerCode="2052" identifier="MQCA_CF_STRUC_DESC"/>
			<Parameter name="Recovery" type="int" integerCode="71" identifier="MQIA_CF_RECOVER"/>
			<Parameter name="Replace" type="int" integerCode="1006" identifier="MQIACF_REPLACE"/>
		</RequestParameters>
	</Command>

	<Command name="COPY_CF_STRUC" integerCode="110" identifier="MQCMD_COPY_CF_STRUC">
		<RequestParameters>
			<Parameter name="FromCFStrucName" integerCode="3093" identifier="MQCACF_FROM_CF_STRUC_NAME" type="string" required="true"/>
			<Parameter name="ToCFStrucName" integerCode="3094" identifier="MQCACF_TO_CF_STRUC_NAME" type="string" required="true"/>

			<Parameter name="CFLevel" type="int" integerCode="70" identifier="MQIA_CF_LEVEL"/>
			<Parameter name="CFStrucDesc" type="string" integerCode="2052" identifier="MQCA_CF_STRUC_DESC"/>
			<Parameter name="Recovery" type="int" integerCode="71" identifier="MQIA_CF_RECOVER"/>
			<Parameter name="Replace" type="int" integerCode="1006" identifier="MQIACF_REPLACE"/>
		</RequestParameters>
	</Command>


	<Command name="CREATE_CF_STRUC" integerCode="108" identifier="MQCMD_CREATE_CF_STRUC">
		<RequestParameters>
			<Parameter name="CFStrucName" integerCode="2039" identifier="MQCA_CF_STRUC_NAME" type="string" required="true"/>

			<Parameter name="CFLevel" type="int" integerCode="70" identifier="MQIA_CF_LEVEL"/>
			<Parameter name="CFStrucDesc" type="string" integerCode="2052" identifier="MQCA_CF_STRUC_DESC"/>
			<Parameter name="Recovery" type="int" integerCode="71" identifier="MQIA_CF_RECOVER"/>
			<Parameter name="Replace" type="int" integerCode="1006" identifier="MQIACF_REPLACE"/>
		</RequestParameters>
	</Command>


	<!-- Change, Copy and Create Channel -->
	<Command name="CHANGE_CHANNEL" integerCode="21" identifier="MQCMD_CHANGE_CHANNEL">
		<RequestParameters>
			<Parameter name="ChannelName" integerCode="3501" identifier="MQCACH_CHANNEL_NAME" type="string" required="true"/>
			<Parameter name="ChannelType" integerCode="1511" identifier="MQIACH_CHANNEL_TYPE" type="int" required="true"/>

			<Parameter name="BatchHeartbeat" integerCode="1567" identifier="MQIACH_BATCH_HB" type="int"/>
			<Parameter name="BatchInterval" integerCode="1564" identifier="MQIACH_BATCH_INTERVAL" type="int"/>
			<Parameter name="BatchSize" integerCode="1502" identifier="MQIACH_BATCH_SIZE" type="int"/>
			<Parameter name="ChannelDesc" integerCode="3502" identifier="MQCACH_DESC" type="string"/>
			<Parameter name="ChannelMonitoring" integerCode="122" identifier="MQIA_MONITORING_CHANNEL" type="int"/>
			<Parameter name="ChannelStatistics" integerCode="129" identifier="MQIA_STATISTICS_CHANNEL" type="int"/>
			<Parameter name="ClusterName" integerCode="2029" identifier="MQCA_CLUSTER_NAME" type="string"/>
			<Parameter name="ClusterNamelist" integerCode="2030" identifier="MQCA_CLUSTER_NAMELIST" type="string[]"/>
			<Parameter name="CLWLChannelPriority" integerCode="1578" identifier="MQIACH_CLWL_CHANNEL_PRIORITY" type="int"/>
			<Parameter name="CLWLChannelRank" integerCode="1577" identifier="MQIACH_CLWL_CHANNEL_RANK" type="int"/>
			<Parameter name="CLWLChannelWeight" integerCode="1579" identifier="MQIACH_CLWL_CHANNEL_WEIGHT" type="int"/>
			<Parameter name="CommandScope" integerCode="3080" identifier="MQCACF_COMMAND_SCOPE" type="string"/>
			<Parameter name="ConnectionName" integerCode="3506" identifier="MQCACH_CONNECTION_NAME" type="string"/>
			<Parameter name="DataConversion" integerCode="1515" identifier="MQIACH_DATA_CONVERSION" type="int"/>
			<Parameter name="DiscInterval" integerCode="1503" identifier="MQIACH_DISC_INTERVAL" type="int[]"/>
			<Parameter name="HeaderCompression" integerCode="1575" identifier="MQIACH_HDR_COMPRESSION" type="int"/>
			<Parameter name="HeartbeatInterval" integerCode="1563" identifier="MQIACH_HB_INTERVAL" type="int"/>
			<Parameter name="KeepAliveInterval" integerCode="1566" identifier="MQIACH_KEEP_ALIVE_INTERVAL" type="int"/>
			<Parameter name="LocalAddress" integerCode="3520" identifier="MQCACH_LOCAL_ADDRESS" type="string"/>
			<Parameter name="LongRetryCount" integerCode="1507" identifier="MQIACH_LONG_RETRY" type="int"/>
			<Parameter name="LongRetryInterval" integerCode="1506" identifier="MQIACH_LONG_TIMER" type="int"/>
			<Parameter name="MaxMsgLength" integerCode="1510" identifier="MQIACH_MAX_MSG_LENGTH" type="int"/>
			<Parameter name="MCAName" integerCode="3507" identifier="MQCACH_MCA_NAME" type="int"/>
			<Parameter name="MCAType" integerCode="1517" identifier="MQIACH_MCA_TYPE" type="int"/>
			<Parameter name="MCAUserIdentifier" integerCode="3527" identifier="MQCACH_MCA_USER_ID" type="string"/>
			<Parameter name="MessageCompression" integerCode="1576" identifier="MQIACH_MSG_COMPRESSION" type="int[]"/>
			<Parameter name="ModeName" integerCode="3503" identifier="MQCACH_MODE_NAME" type="string"/>
			<Parameter name="MsgExit" integerCode="3509" identifier="MQCACH_MSG_EXIT_NAME" type="string[]"/>
			<Parameter name="MsgRetryCount" integerCode="1544" identifier="MQIACH_MR_COUNT" type="int"/>
			<Parameter name="MsgRetryExit" integerCode="3534" identifier="MQCACH_MR_EXIT_NAME" type="string"/>
			<Parameter name="MsgRetryInterval" integerCode="1545" identifier="MQIACH_MR_INTERVAL" type="int"/>
			<Parameter name="MsgRetryUserData" integerCode="3535" identifier="MQCACH_MR_EXIT_USER_DATA" type="string"/>
			<Parameter name="MsgUserData" integerCode="3514" identifier="MQCACH_MSG_EXIT_USER_DATA" type="string[]"/>
			<Parameter name="NetworkPriority" integerCode="1565" identifier="MQIACH_NETWORK_PRIORITY" type="int"/>
			<Parameter name="NonPersistentMsgSpeed" integerCode="1562" identifier="MQIACH_NPM_SPEED" type="int"/>
			<Parameter name="Password" integerCode="3518" identifier="MQCACH_PASSWORD" type="string"/>
			<Parameter name="PutAuthority" integerCode="1508" identifier="MQIACH_PUT_AUTHORITY" type="int"/>
			<Parameter name="QMgrName" integerCode="2015" identifier="MQCA_Q_MGR_NAME" type="string"/>
			<Parameter name="QSGDisposition" integerCode="63" identifier="MQIA_QSG_DISP" type="int"/>
			<Parameter name="ReceiveExit" integerCode="3511" identifier="MQCACH_RCV_EXIT_NAME" type="string[]"/>
			<Parameter name="ReceiveUserData" integerCode="3516" identifier="MQCACH_RCV_EXIT_USER_DATA" type="string[]"/>
			<Parameter name="Replace" integerCode="1006" identifier="MQIACF_REPLACE" type="int"/>
			<Parameter name="SecurityExit" integerCode="3508" identifier="MQCACH_SEC_EXIT_NAME" type="string"/>
			<Parameter name="SecurityUserData" integerCode="3513" identifier="MQCACH_SEC_EXIT_USER_DATA" type="string"/>
			<Parameter name="SendExit" integerCode="3510" identifier="MQCACH_SEND_EXIT_NAME" type="string[]"/>
			<Parameter name="SendUserData" integerCode="3515" identifier="MQCACH_SEND_EXIT_USER_DATA" type="string[]"/>
			<Parameter name="SeqNumberWrap" integerCode="1509" identifier="MQIACH_SEQUENCE_NUMBER_WRAP" type="int"/>
			<Parameter name="ShortRetryCount" integerCode="1505" identifier="MQIACH_SHORT_RETRY" type="int"/>
			<Parameter name="ShortRetryInterval" integerCode="1504" identifier="MQIACH_SHORT_TIMER" type="int"/>
			<Parameter name="SSLCipherSpec" integerCode="3544" identifier="MQCACH_SSL_CIPHER_SPEC" type="string"/>
			<Parameter name="SSLClientAuth" integerCode="1568" identifier="MQIACH_SSL_CLIENT_AUTH" type="int"/>
			<Parameter name="SSLPeerName" integerCode="3545" identifier="MQCACH_SSL_PEER_NAME" type="string"/>
			<Parameter name="TpName" integerCode="3504" identifier="MQCACH_TP_NAME" type="string"/>
			<Parameter name="TransportType" integerCode="1501" identifier="MQIACH_XMIT_PROTOCOL_TYPE" type="int"/>
			<Parameter name="UserIdentifier" integerCode="3517" identifier="MQCACH_USER_ID" type="string"/>
			<Parameter name="XmitQName" integerCode="3505" identifier="MQCACH_XMIT_Q_NAME" type="string"/>
		</RequestParameters>
	</Command>

	<Command name="CREATE_CHANNEL" integerCode="23" identifier="MQCMD_CREATE_CHANNEL">
		<RequestParameters>
			<Parameter name="ChannelName" integerCode="3501" identifier="MQCACH_CHANNEL_NAME" type="string" required="true"/>
			<Parameter name="ChannelType" integerCode="1511" identifier="MQIACH_CHANNEL_TYPE" type="int" required="true"/>

			<Parameter name="BatchHeartbeat" integerCode="1567" identifier="MQIACH_BATCH_HB" type="int"/>
			<Parameter name="BatchInterval" integerCode="1564" identifier="MQIACH_BATCH_INTERVAL" type="int"/>
			<Parameter name="BatchSize" integerCode="1502" identifier="MQIACH_BATCH_SIZE" type="int"/>
			<Parameter name="ChannelDesc" integerCode="3502" identifier="MQCACH_DESC" type="string"/>
			<Parameter name="ChannelMonitoring" integerCode="122" identifier="MQIA_MONITORING_CHANNEL" type="int"/>
			<Parameter name="ChannelStatistics" integerCode="129" identifier="MQIA_STATISTICS_CHANNEL" type="int"/>
			<Parameter name="ClusterName" integerCode="2029" identifier="MQCA_CLUSTER_NAME" type="string"/>
			<Parameter name="ClusterNamelist" integerCode="2030" identifier="MQCA_CLUSTER_NAMELIST" type="string[]"/>
			<Parameter name="CLWLChannelPriority" integerCode="1578" identifier="MQIACH_CLWL_CHANNEL_PRIORITY" type="int"/>
			<Parameter name="CLWLChannelRank" integerCode="1577" identifier="MQIACH_CLWL_CHANNEL_RANK" type="int"/>
			<Parameter name="CLWLChannelWeight" integerCode="1579" identifier="MQIACH_CLWL_CHANNEL_WEIGHT" type="int"/>
			<Parameter name="CommandScope" integerCode="3080" identifier="MQCACF_COMMAND_SCOPE" type="string"/>
			<Parameter name="ConnectionName" integerCode="3506" identifier="MQCACH_CONNECTION_NAME" type="string"/>
			<Parameter name="DataConversion" integerCode="1515" identifier="MQIACH_DATA_CONVERSION" type="int"/>
			<Parameter name="DiscInterval" integerCode="1503" identifier="MQIACH_DISC_INTERVAL" type="int[]"/>
			<Parameter name="HeaderCompression" integerCode="1575" identifier="MQIACH_HDR_COMPRESSION" type="int"/>
			<Parameter name="HeartbeatInterval" integerCode="1563" identifier="MQIACH_HB_INTERVAL" type="int"/>
			<Parameter name="KeepAliveInterval" integerCode="1566" identifier="MQIACH_KEEP_ALIVE_INTERVAL" type="int"/>
			<Parameter name="LocalAddress" integerCode="3520" identifier="MQCACH_LOCAL_ADDRESS" type="string"/>
			<Parameter name="LongRetryCount" integerCode="1507" identifier="MQIACH_LONG_RETRY" type="int"/>
			<Parameter name="LongRetryInterval" integerCode="1506" identifier="MQIACH_LONG_TIMER" type="int"/>
			<Parameter name="MaxMsgLength" integerCode="1510" identifier="MQIACH_MAX_MSG_LENGTH" type="int"/>
			<Parameter name="MCAName" integerCode="3507" identifier="MQCACH_MCA_NAME" type="int"/>
			<Parameter name="MCAType" integerCode="1517" identifier="MQIACH_MCA_TYPE" type="int"/>
			<Parameter name="MCAUserIdentifier" integerCode="3527" identifier="MQCACH_MCA_USER_ID" type="string"/>
			<Parameter name="MessageCompression" integerCode="1576" identifier="MQIACH_MSG_COMPRESSION" type="int[]"/>
			<Parameter name="ModeName" integerCode="3503" identifier="MQCACH_MODE_NAME" type="string"/>
			<Parameter name="MsgExit" integerCode="3509" identifier="MQCACH_MSG_EXIT_NAME" type="string[]"/>
			<Parameter name="MsgRetryCount" integerCode="1544" identifier="MQIACH_MR_COUNT" type="int"/>
			<Parameter name="MsgRetryExit" integerCode="3534" identifier="MQCACH_MR_EXIT_NAME" type="string"/>
			<Parameter name="MsgRetryInterval" integerCode="1545" identifier="MQIACH_MR_INTERVAL" type="int"/>
			<Parameter name="MsgRetryUserData" integerCode="3535" identifier="MQCACH_MR_EXIT_USER_DATA" type="string"/>
			<Parameter name="MsgUserData" integerCode="3514" identifier="MQCACH_MSG_EXIT_USER_DATA" type="string[]"/>
			<Parameter name="NetworkPriority" integerCode="1565" identifier="MQIACH_NETWORK_PRIORITY" type="int"/>
			<Parameter name="NonPersistentMsgSpeed" integerCode="1562" identifier="MQIACH_NPM_SPEED" type="int"/>
			<Parameter name="Password" integerCode="3518" identifier="MQCACH_PASSWORD" type="string"/>
			<Parameter name="PutAuthority" integerCode="1508" identifier="MQIACH_PUT_AUTHORITY" type="int"/>
			<Parameter name="QMgrName" integerCode="2015" identifier="MQCA_Q_MGR_NAME" type="string"/>
			<Parameter name="QSGDisposition" integerCode="63" identifier="MQIA_QSG_DISP" type="int"/>
			<Parameter name="ReceiveExit" integerCode="3511" identifier="MQCACH_RCV_EXIT_NAME" type="string[]"/>
			<Parameter name="ReceiveUserData" integerCode="3516" identifier="MQCACH_RCV_EXIT_USER_DATA" type="string[]"/>
			<Parameter name="Replace" integerCode="1006" identifier="MQIACF_REPLACE" type="int"/>
			<Parameter name="SecurityExit" integerCode="3508" identifier="MQCACH_SEC_EXIT_NAME" type="string"/>
			<Parameter name="SecurityUserData" integerCode="3513" identifier="MQCACH_SEC_EXIT_USER_DATA" type="string"/>
			<Parameter name="SendExit" integerCode="3510" identifier="MQCACH_SEND_EXIT_NAME" type="string[]"/>
			<Parameter name="SendUserData" integerCode="3515" identifier="MQCACH_SEND_EXIT_USER_DATA" type="string[]"/>
			<Parameter name="SeqNumberWrap" integerCode="1509" identifier="MQIACH_SEQUENCE_NUMBER_WRAP" type="int"/>
			<Parameter name="ShortRetryCount" integerCode="1505" identifier="MQIACH_SHORT_RETRY" type="int"/>
			<Parameter name="ShortRetryInterval" integerCode="1504" identifier="MQIACH_SHORT_TIMER" type="int"/>
			<Parameter name="SSLCipherSpec" integerCode="3544" identifier="MQCACH_SSL_CIPHER_SPEC" type="string"/>
			<Parameter name="SSLClientAuth" integerCode="1568" identifier="MQIACH_SSL_CLIENT_AUTH" type="int"/>
			<Parameter name="SSLPeerName" integerCode="3545" identifier="MQCACH_SSL_PEER_NAME" type="string"/>
			<Parameter name="TpName" integerCode="3504" identifier="MQCACH_TP_NAME" type="string"/>
			<Parameter name="TransportType" integerCode="1501" identifier="MQIACH_XMIT_PROTOCOL_TYPE" type="int"/>
			<Parameter name="UserIdentifier" integerCode="3517" identifier="MQCACH_USER_ID" type="string"/>
			<Parameter name="XmitQName" integerCode="3505" identifier="MQCACH_XMIT_Q_NAME" type="string"/>
		</RequestParameters>
	</Command>

	<Command name="COPY_CHANNEL" integerCode="22" identifier="MQCMD_COPY_CHANNEL">
		<RequestParameters>
			<Parameter name="FromChannelName" integerCode="3007" identifier="MQCACF_FROM_CHANNEL_NAME" type="string" required="true"/>
			<Parameter name="ToChannelName" integerCode="3008" identifier="MQCACF_TO_CHANNEL_NAME" type="string" required="true"/>
			<Parameter name="ChannelType" integerCode="1511" identifier="MQIACH_CHANNEL_TYPE" type="int" required="true"/>

			<Parameter name="BatchHeartbeat" integerCode="1567" identifier="MQIACH_BATCH_HB" type="int"/>
			<Parameter name="BatchInterval" integerCode="1564" identifier="MQIACH_BATCH_INTERVAL" type="int"/>
			<Parameter name="BatchSize" integerCode="1502" identifier="MQIACH_BATCH_SIZE" type="int"/>
			<Parameter name="ChannelDesc" integerCode="3502" identifier="MQCACH_DESC" type="string"/>
			<Parameter name="ChannelMonitoring" integerCode="122" identifier="MQIA_MONITORING_CHANNEL" type="int"/>
			<Parameter name="ChannelStatistics" integerCode="129" identifier="MQIA_STATISTICS_CHANNEL" type="int"/>
			<Parameter name="ClusterName" integerCode="2029" identifier="MQCA_CLUSTER_NAME" type="string"/>
			<Parameter name="ClusterNamelist" integerCode="2030" identifier="MQCA_CLUSTER_NAMELIST" type="string[]"/>
			<Parameter name="CLWLChannelPriority" integerCode="1578" identifier="MQIACH_CLWL_CHANNEL_PRIORITY" type="int"/>
			<Parameter name="CLWLChannelRank" integerCode="1577" identifier="MQIACH_CLWL_CHANNEL_RANK" type="int"/>
			<Parameter name="CLWLChannelWeight" integerCode="1579" identifier="MQIACH_CLWL_CHANNEL_WEIGHT" type="int"/>
			<Parameter name="CommandScope" integerCode="3080" identifier="MQCACF_COMMAND_SCOPE" type="string"/>
			<Parameter name="ConnectionName" integerCode="3506" identifier="MQCACH_CONNECTION_NAME" type="string"/>
			<Parameter name="DataConversion" integerCode="1515" identifier="MQIACH_DATA_CONVERSION" type="int"/>
			<Parameter name="DiscInterval" integerCode="1503" identifier="MQIACH_DISC_INTERVAL" type="int[]"/>
			<Parameter name="HeaderCompression" integerCode="1575" identifier="MQIACH_HDR_COMPRESSION" type="int"/>
			<Parameter name="HeartbeatInterval" integerCode="1563" identifier="MQIACH_HB_INTERVAL" type="int"/>
			<Parameter name="KeepAliveInterval" integerCode="1566" identifier="MQIACH_KEEP_ALIVE_INTERVAL" type="int"/>
			<Parameter name="LocalAddress" integerCode="3520" identifier="MQCACH_LOCAL_ADDRESS" type="string"/>
			<Parameter name="LongRetryCount" integerCode="1507" identifier="MQIACH_LONG_RETRY" type="int"/>
			<Parameter name="LongRetryInterval" integerCode="1506" identifier="MQIACH_LONG_TIMER" type="int"/>
			<Parameter name="MaxMsgLength" integerCode="1510" identifier="MQIACH_MAX_MSG_LENGTH" type="int"/>
			<Parameter name="MCAName" integerCode="3507" identifier="MQCACH_MCA_NAME" type="int"/>
			<Parameter name="MCAType" integerCode="1517" identifier="MQIACH_MCA_TYPE" type="int"/>
			<Parameter name="MCAUserIdentifier" integerCode="3527" identifier="MQCACH_MCA_USER_ID" type="string"/>
			<Parameter name="MessageCompression" integerCode="1576" identifier="MQIACH_MSG_COMPRESSION" type="int[]"/>
			<Parameter name="ModeName" integerCode="3503" identifier="MQCACH_MODE_NAME" type="string"/>
			<Parameter name="MsgExit" integerCode="3509" identifier="MQCACH_MSG_EXIT_NAME" type="string[]"/>
			<Parameter name="MsgRetryCount" integerCode="1544" identifier="MQIACH_MR_COUNT" type="int"/>
			<Parameter name="MsgRetryExit" integerCode="3534" identifier="MQCACH_MR_EXIT_NAME" type="string"/>
			<Parameter name="MsgRetryInterval" integerCode="1545" identifier="MQIACH_MR_INTERVAL" type="int"/>
			<Parameter name="MsgRetryUserData" integerCode="3535" identifier="MQCACH_MR_EXIT_USER_DATA" type="string"/>
			<Parameter name="MsgUserData" integerCode="3514" identifier="MQCACH_MSG_EXIT_USER_DATA" type="string[]"/>
			<Parameter name="NetworkPriority" integerCode="1565" identifier="MQIACH_NETWORK_PRIORITY" type="int"/>
			<Parameter name="NonPersistentMsgSpeed" integerCode="1562" identifier="MQIACH_NPM_SPEED" type="int"/>
			<Parameter name="Password" integerCode="3518" identifier="MQCACH_PASSWORD" type="string"/>
			<Parameter name="PutAuthority" integerCode="1508" identifier="MQIACH_PUT_AUTHORITY" type="int"/>
			<Parameter name="QMgrName" integerCode="2015" identifier="MQCA_Q_MGR_NAME" type="string"/>
			<Parameter name="QSGDisposition" integerCode="63" identifier="MQIA_QSG_DISP" type="int"/>
			<Parameter name="ReceiveExit" integerCode="3511" identifier="MQCACH_RCV_EXIT_NAME" type="string[]"/>
			<Parameter name="ReceiveUserData" integerCode="3516" identifier="MQCACH_RCV_EXIT_USER_DATA" type="string[]"/>
			<Parameter name="Replace" integerCode="1006" identifier="MQIACF_REPLACE" type="int"/>
			<Parameter name="SecurityExit" integerCode="3508" identifier="MQCACH_SEC_EXIT_NAME" type="string"/>
			<Parameter name="SecurityUserData" integerCode="3513" identifier="MQCACH_SEC_EXIT_USER_DATA" type="string"/>
			<Parameter name="SendExit" integerCode="3510" identifier="MQCACH_SEND_EXIT_NAME" type="string[]"/>
			<Parameter name="SendUserData" integerCode="3515" identifier="MQCACH_SEND_EXIT_USER_DATA" type="string[]"/>
			<Parameter name="SeqNumberWrap" integerCode="1509" identifier="MQIACH_SEQUENCE_NUMBER_WRAP" type="int"/>
			<Parameter name="ShortRetryCount" integerCode="1505" identifier="MQIACH_SHORT_RETRY" type="int"/>
			<Parameter name="ShortRetryInterval" integerCode="1504" identifier="MQIACH_SHORT_TIMER" type="int"/>
			<Parameter name="SSLCipherSpec" integerCode="3544" identifier="MQCACH_SSL_CIPHER_SPEC" type="string"/>
			<Parameter name="SSLClientAuth" integerCode="1568" identifier="MQIACH_SSL_CLIENT_AUTH" type="int"/>
			<Parameter name="SSLPeerName" integerCode="3545" identifier="MQCACH_SSL_PEER_NAME" type="string"/>
			<Parameter name="TpName" integerCode="3504" identifier="MQCACH_TP_NAME" type="string"/>
			<Parameter name="TransportType" integerCode="1501" identifier="MQIACH_XMIT_PROTOCOL_TYPE" type="int"/>
			<Parameter name="UserIdentifier" integerCode="3517" identifier="MQCACH_USER_ID" type="string"/>
			<Parameter name="XmitQName" integerCode="3505" identifier="MQCACH_XMIT_Q_NAME" type="string"/>
		</RequestParameters>
	</Command>

	<!-- Change, Copy, and Create Channel Listener -->

	<Command name="CHANGE_LISTENER" integerCode="93" identifier="MQCMD_CHANGE_LISTENER">
		<RequestParameters>
			<Parameter name="ListenerName" integerCode="3554" identifier="MQCACH_LISTENER_NAME" type="string" required="true"/>
			<Parameter name="TransportType" integerCode="1501" identifier="MQIACH_XMIT_PROTOCOL_TYPE" type="int" required="true"/>

			<Parameter name="Adapter" integerCode="1519" identifier="MQIACH_ADAPTER" type="int"/>
			<Parameter name="Backlog" integerCode="1602" identifier="MQIACH_BACKLOG" type="int"/>
			<Parameter name="Commands" integerCode="1520" identifier="MQIACH_COMMAND_COUNT" type="int"/>
			<Parameter name="IPAddress" integerCode="3552" identifier="MQCACH_IP_ADDRESS" type="string"/>
			<Parameter name="ListenerDesc" integerCode="3555" identifier="MQCACH_LISTENER_DESC" type="string"/>
			<Parameter name="LocalName" integerCode="3521" identifier="MQCACH_LOCAL_NAME" type="string"/>
			<Parameter name="NetbiosNames" integerCode="1513" identifier="MQIACH_NAME_COUNT" type="int"/>
			<Parameter name="Port" integerCode="1522" identifier="MQIACH_PORT" type="int"/>
			<Parameter name="Replace" integerCode="1006" identifier="MQIACF_REPLACE" type="int"/>
			<Parameter name="Sessions" integerCode="1518" identifier="MQIACH_SESSION_COUNT" type="int"/>
			<Parameter name="Socket" integerCode="1521" identifier="MQIACH_SOCKET" type="int"/>
			<Parameter name="StartMode" integerCode="1601" identifier="MQIACH_LISTENER_CONTROL" type="int"/>
			<Parameter name="TPname" integerCode="3504" identifier="MQCACH_TP_NAME" type="string"/>
		</RequestParameters>
	</Command>

	<Command name="COPY_LISTENER" integerCode="94" identifier="MQCMD_COPY_LISTENER">
		<RequestParameters>
			<Parameter name="FromListenerName" integerCode="3124" identifier="MQCACF_FROM_LISTENER_NAME" type="string" required="true"/>
			<Parameter name="ToListenerName" integerCode="3125" identifier="MQCACF_TO_LISTENER_NAME"  type="string" required="true"/>

			<Parameter name="Adapter" integerCode="1519" identifier="MQIACH_ADAPTER" type="int"/>
			<Parameter name="Backlog" integerCode="1602" identifier="MQIACH_BACKLOG" type="int"/>
			<Parameter name="Commands" integerCode="1520" identifier="MQIACH_COMMAND_COUNT" type="int"/>
			<Parameter name="IPAddress" integerCode="3552" identifier="MQCACH_IP_ADDRESS" type="string"/>
			<Parameter name="ListenerDesc" integerCode="3555" identifier="MQCACH_LISTENER_DESC" type="string"/>
			<Parameter name="LocalName" integerCode="3521" identifier="MQCACH_LOCAL_NAME" type="string"/>
			<Parameter name="NetbiosNames" integerCode="1513" identifier="MQIACH_NAME_COUNT" type="int"/>
			<Parameter name="Port" integerCode="1522" identifier="MQIACH_PORT" type="int"/>
			<Parameter name="Replace" integerCode="1006" identifier="MQIACF_REPLACE" type="int"/>
			<Parameter name="Sessions" integerCode="1518" identifier="MQIACH_SESSION_COUNT" type="int"/>
			<Parameter name="Socket" integerCode="1521" identifier="MQIACH_SOCKET" type="int"/>
			<Parameter name="StartMode" integerCode="1601" identifier="MQIACH_LISTENER_CONTROL" type="int"/>
			<Parameter name="TPname" integerCode="3504" identifier="MQCACH_TP_NAME" type="string"/>

		</RequestParameters>
	</Command>

	<Command name="CREATE_LISTENER" integerCode="95" identifier="MQCMD_CREATE_LISTENER">
		<RequestParameters>
			<Parameter name="ListenerName" integerCode="3554" identifier="MQCACH_LISTENER_NAME" type="string" required="true"/>
			<Parameter name="TransportType" integerCode="1501" identifier="MQIACH_XMIT_PROTOCOL_TYPE" type="int" required="true"/>

			<Parameter name="Adapter" integerCode="1519" identifier="MQIACH_ADAPTER" type="int"/>
			<Parameter name="Backlog" integerCode="1602" identifier="MQIACH_BACKLOG" type="int"/>
			<Parameter name="Commands" integerCode="1520" identifier="MQIACH_COMMAND_COUNT" type="int"/>
			<Parameter name="IPAddress" integerCode="3552" identifier="MQCACH_IP_ADDRESS" type="string"/>
			<Parameter name="ListenerDesc" integerCode="3555" identifier="MQCACH_LISTENER_DESC" type="string"/>
			<Parameter name="LocalName" integerCode="3521" identifier="MQCACH_LOCAL_NAME" type="string"/>
			<Parameter name="NetbiosNames" integerCode="1513" identifier="MQIACH_NAME_COUNT" type="int"/>
			<Parameter name="Port" integerCode="1522" identifier="MQIACH_PORT" type="int"/>
			<Parameter name="Replace" integerCode="1006" identifier="MQIACF_REPLACE" type="int"/>
			<Parameter name="Sessions" integerCode="1518" identifier="MQIACH_SESSION_COUNT" type="int"/>
			<Parameter name="Socket" integerCode="1521" identifier="MQIACH_SOCKET" type="int"/>
			<Parameter name="StartMode" integerCode="1601" identifier="MQIACH_LISTENER_CONTROL" type="int"/>
			<Parameter name="TPname" integerCode="3504" identifier="MQCACH_TP_NAME" type="string"/>

		</RequestParameters>
	</Command>

	<!-- Change, Copy, and Create Namelist -->